### ISSUE TITLE
xlib error when running from command line

### ISSUE THREAD

**Issue by AJdeMooij** [UiL-OTS-labs-backoffice/UiL-OTS-Video-Coding-System#34]
This process is probably using LibVLC incorrectly.
Pass "--no-xlib" to libvlc_new() to fix this.
../../../include/vlc_xlib.h:46:vlc_xlib_init: Xlib not initialized for threads.

This error is also present when not running from the command line, but it only shows up when it is ran that way

**Comment by tymees** [comment]
Problem solved by updating to VLCJ 4, as far as I can see
